# Descriptions are not added as labels are self-explanatory

# Statuses
- name: "identified"
  color: "C0E895"
- name: "in review"
  color: "AEC6FC"
- name: "needs reproduction"
  color: "C76A38"
- name: "has PR"
  color: "8958e5"
- name: "blocked"
  color: "E61515"
- name: "wontfix"
  color: "ffffff"

# Types
- name: "bug"
  color: "DC4545"
- name: "feature request"
  color: "DEAEFC"

# Apps
- name: "apps: website"
  color: "62CFE7"
- name: "apps: bot"
  color: "62CFE7"
- name: "github"
  color: "62CFE7"

# Semver
- name: "semver: major"
  color: "AB1947"
- name: "semver: minor"
  color: "C9D67E"
- name: "semver: patch"
  color: "E1BE94"

# Misc
- name: "urgent"
  color: "B60205"
- name: "regression"
  color: "E66C5F"
- name: "performance"
  color: "41BF78"
- name: "refactor"
  color: "3B73AE"
- name: "duplicate"
  color: "D0CFCA"
- name: "dependency"
  color: "4968C6"
- name: "security"
  color: "B81B1B"
- name: "invalid"
  color: "ffffff"
