name: Feature request
description: Suggest an idea for this project
labels: ["feature request"]
body:
  - type: markdown
    attributes:
      value: |
        Questions? Ask in our Discord server: https://discord.gg/FJ5DMEb8zA
  - type: dropdown
    attributes:
      label: Which application is this feature request for?
      multiple: false
      options:
        - "BobTheBot"
        - "Website"
        - "Other/GitHub"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the feature
      description: A clear and concise description of what the feature is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggested implementation
      description: A clear and concise description of how you would like this feature to be implemented.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
